// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOy_cf6JDS_NRfEo-6st_7iGbVoJBOorY',
    appId: '1:76431284610:web:a62ebf6a58e6c80b8e179b',
    messagingSenderId: '76431284610',
    projectId: 'the-daily-journal-bbbf4',
    authDomain: 'the-daily-journal-bbbf4.firebaseapp.com',
    storageBucket: 'the-daily-journal-bbbf4.appspot.com',
    measurementId: 'G-S8DG34NVWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5nr7nB65c6TiELurEVT4dBuubCxdKyB4',
    appId: '1:76431284610:android:e27a6ef420a686958e179b',
    messagingSenderId: '76431284610',
    projectId: 'the-daily-journal-bbbf4',
    storageBucket: 'the-daily-journal-bbbf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtOt82907-Lcks2D7e_jvPGmP95e8_WQ',
    appId: '1:76431284610:ios:cb3b3e8240a697108e179b',
    messagingSenderId: '76431284610',
    projectId: 'the-daily-journal-bbbf4',
    storageBucket: 'the-daily-journal-bbbf4.appspot.com',
    iosClientId: '76431284610-f1jgtiu8e3eaqgpautkjvh43do18pd8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.theDailyJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtOt82907-Lcks2D7e_jvPGmP95e8_WQ',
    appId: '1:76431284610:ios:713dcec48a1591818e179b',
    messagingSenderId: '76431284610',
    projectId: 'the-daily-journal-bbbf4',
    storageBucket: 'the-daily-journal-bbbf4.appspot.com',
    iosClientId: '76431284610-p8r93a24ido49b4ev485np01bs65ovsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.theDailyJournal.RunnerTests',
  );
}
