// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Viwt_ThixKM10p0ghEif1sI_CvLrYHQ',
    appId: '1:1041768734596:android:49c84d9a6eb007954787d1',
    messagingSenderId: '1041768734596',
    projectId: 'the-daily-journal-90f99',
    storageBucket: 'the-daily-journal-90f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvNNpfJ3UckexxdBC1tSAXsV3N5D1NSc',
    appId: '1:1041768734596:ios:70b1d5206cd24f1e4787d1',
    messagingSenderId: '1041768734596',
    projectId: 'the-daily-journal-90f99',
    storageBucket: 'the-daily-journal-90f99.appspot.com',
    androidClientId: '1041768734596-437k2ccrg2or2iti65ca3o4e77vfmhvo.apps.googleusercontent.com',
    iosClientId: '1041768734596-i2l9qdui1641aaceo2676did7r2j7agi.apps.googleusercontent.com',
    iosBundleId: 'com.example.theDailyJournal',
  );
}
